// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAPI.Data;

namespace RealEstateAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "a2c32877-b61b-4537-84a2-36c7de3d5d0b",
                            ConcurrencyStamp = "0adb08bf-2451-48b5-a047-043f20781c92",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "08059ab0-af7b-4e5b-89ca-88a92581bb99",
                            ConcurrencyStamp = "26af4332-95ba-4497-b519-b8cdeb38ce62",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 993, DateTimeKind.Local).AddTicks(4240),
                            Title = "Vilnius"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 993, DateTimeKind.Local).AddTicks(4963),
                            Title = "Kaunas"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 993, DateTimeKind.Local).AddTicks(4976),
                            Title = "Klaipėda"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 993, DateTimeKind.Local).AddTicks(4980),
                            Title = "Palanga"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 993, DateTimeKind.Local).AddTicks(4982),
                            Title = "Šiauliai"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 993, DateTimeKind.Local).AddTicks(4985),
                            Title = "Druskininkai"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 992, DateTimeKind.Local).AddTicks(8814),
                            Title = "Lithuania"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.FavouriteProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouriteProperties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4290),
                            PropertyId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4833),
                            PropertyId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4844),
                            PropertyId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4852),
                            PropertyId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4855),
                            PropertyId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4858),
                            PropertyId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4861),
                            PropertyId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4864),
                            PropertyId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4867),
                            PropertyId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 995, DateTimeKind.Local).AddTicks(4870),
                            PropertyId = 2,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("RentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Gedimino g. 71",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8387),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 350f,
                            PropertyTypeId = 2,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius G71",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gedimino g. 72",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8710),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 369f,
                            PropertyTypeId = 2,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius G72",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gedimino g. 73",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8726),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 400f,
                            PropertyTypeId = 2,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius K73",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Gedimino g. 74",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8730),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 350f,
                            PropertyTypeId = 2,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius K74",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "Gedimino g. 75",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8733),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 500f,
                            PropertyTypeId = 2,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius K75",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "Rygos g. 10",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8736),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 600f,
                            PropertyTypeId = 4,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius R10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "Rygos g. 11",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8740),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 550f,
                            PropertyTypeId = 4,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius R11",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "Rygos g. 12",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8743),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 589f,
                            PropertyTypeId = 4,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius R12",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "Rygos g. 13",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8746),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 600f,
                            PropertyTypeId = 4,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius R13",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Address = "Rygos g. 14",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8749),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 650f,
                            PropertyTypeId = 4,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius R14",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Address = "Rygos g. 15",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8752),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 550f,
                            PropertyTypeId = 4,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius R15",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Address = "Justiniškių g. 10",
                            CityId = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 994, DateTimeKind.Local).AddTicks(8755),
                            Description = "Certainty listening no no behaviour existence assurance situation is. Because add why not esteems amiable him. Interested the unaffected mrs law friendship add principles. Indeed on people do merits to. Court heard which up above hoped grave do. Answer living law things either sir bed length. Looked before we an on merely. These no death he at share alone. Yet outward the him compass hearted are tedious.",
                            Price = 450f,
                            PropertyTypeId = 2,
                            RentTypeId = 1,
                            RoomNumber = 2,
                            Title = "Vilnius J10",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 989, DateTimeKind.Local).AddTicks(3411),
                            Photo = "https://cf.bstatic.com/xdata/images/xphoto/square300/57584488.webp?k=bf724e4e9b9b75480bbe7fc675460a089ba6414fe4693b83ea3fdd8e938832a6&o=",
                            Title = "Hotels"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 991, DateTimeKind.Local).AddTicks(7810),
                            Photo = "https://cf.bstatic.com/static/img/theme-index/carousel_320x240/card-image-apartments_300/9f60235dc09a3ac3f0a93adbc901c61ecd1ce72e.jpg",
                            Title = "Apartments"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 991, DateTimeKind.Local).AddTicks(7837),
                            Photo = "https://cf.bstatic.com/static/img/theme-index/carousel_320x240/bg_resorts/6f87c6143fbd51a0bb5d15ca3b9cf84211ab0884.jpg",
                            Title = "Resorts"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 991, DateTimeKind.Local).AddTicks(7842),
                            Photo = "https://cf.bstatic.com/static/img/theme-index/carousel_320x240/card-image-villas_300/dd0d7f8202676306a661aa4f0cf1ffab31286211.jpg",
                            Title = "Houses"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 991, DateTimeKind.Local).AddTicks(7845),
                            Photo = "https://cf.bstatic.com/xdata/images/city/square250/777085.webp?k=b95bc65ec83682e7aafc89112ff398b1081be9696ef92556ffd4fb9648a6b807&o=",
                            Title = "Lands"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.RentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 992, DateTimeKind.Local).AddTicks(3024),
                            Title = "Long Term"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 12, 10, 18, 19, 56, 992, DateTimeKind.Local).AddTicks(3538),
                            Title = "Short Term"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "lsongulija@gmail.com",
                            FirstName = "Lukas",
                            LastName = "Songulija",
                            Password = "$2a$11$nReFQfy6fjImFdNgiZoEr.3YQBqsIF6Epuj/M0rOjIJuyR9pvnOcu",
                            PhoneNumber = "+37061115217",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "kpigaga@gmail.com",
                            FirstName = "Karolis",
                            LastName = "Pigaga",
                            Password = "$2a$11$.ingiLrjo.XltQt9S4a23OnjsRM4w2hAgtC43ILrWvcP6TSAggDf6",
                            PhoneNumber = "+37061115982",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "epetraitis@gmail.com",
                            FirstName = "Eimantas",
                            LastName = "Petraitis",
                            Password = "$2a$11$3xYunE2p1ld0hq08mRgZMOUO0LwgwNBsMo.xvvkRBQDzLfprg8Zn2",
                            PhoneNumber = "+37061115987",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "jpovas@gmail.com",
                            FirstName = "Jonas",
                            LastName = "Povas",
                            Password = "$2a$11$5zJp/H7Zowz0Mq4Y.2rAxe3WktUYmHLXc3CFxERBaBCwxB9G38VzO",
                            PhoneNumber = "+37061115988",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "jkovas@gmail.com",
                            FirstName = "Jonas",
                            LastName = "Kovas",
                            Password = "$2a$11$25my3oteyKwzRbJ5uJE6/.pNbgYX2j7Fc.mCBRQEJwtG2ysCwB9G2",
                            PhoneNumber = "+37061115989",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = 2,
                            Title = "USER"
                        });
                });

            modelBuilder.Entity("RealEstateAPI.Data.City", b =>
                {
                    b.HasOne("RealEstateAPI.Data.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Comment", b =>
                {
                    b.HasOne("RealEstateAPI.Data.Property", "Property")
                        .WithMany("Comments")
                        .HasForeignKey("PropertyId");

                    b.HasOne("RealEstateAPI.Data.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAPI.Data.FavouriteProperty", b =>
                {
                    b.HasOne("RealEstateAPI.Data.Property", "Property")
                        .WithMany("FavouriteObjects")
                        .HasForeignKey("PropertyId");

                    b.HasOne("RealEstateAPI.Data.User", "User")
                        .WithMany("FavouriteProperties")
                        .HasForeignKey("UserId");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Image", b =>
                {
                    b.HasOne("RealEstateAPI.Data.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Journal", b =>
                {
                    b.HasOne("RealEstateAPI.Data.Property", "Property")
                        .WithMany("Journals")
                        .HasForeignKey("PropertyId");

                    b.HasOne("RealEstateAPI.Data.User", "User")
                        .WithMany("Journals")
                        .HasForeignKey("UserId");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Payment", b =>
                {
                    b.HasOne("RealEstateAPI.Data.Property", "Property")
                        .WithMany("Payments")
                        .HasForeignKey("PropertyId");

                    b.HasOne("RealEstateAPI.Data.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId");

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Property", b =>
                {
                    b.HasOne("RealEstateAPI.Data.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId");

                    b.HasOne("RealEstateAPI.Data.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId");

                    b.HasOne("RealEstateAPI.Data.RentType", "RentType")
                        .WithMany("Properties")
                        .HasForeignKey("RentTypeId");

                    b.HasOne("RealEstateAPI.Data.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId");

                    b.Navigation("City");

                    b.Navigation("PropertyType");

                    b.Navigation("RentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RealEstateAPI.Data.User", b =>
                {
                    b.HasOne("RealEstateAPI.Data.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("TypeId");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("RealEstateAPI.Data.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("RealEstateAPI.Data.Property", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavouriteObjects");

                    b.Navigation("Images");

                    b.Navigation("Journals");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RealEstateAPI.Data.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RealEstateAPI.Data.RentType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RealEstateAPI.Data.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavouriteProperties");

                    b.Navigation("Journals");

                    b.Navigation("Payments");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RealEstateAPI.Data.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
